# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class TC001007(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Chrome(executable_path=r'')
        self.driver.implicitly_wait(30)
        self.base_url = "https://www.google.com/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_t_c001007(self):
        driver = self.driver
        driver.get("https://school.moodledemo.net/")
        driver.find_element_by_link_text("Log in").click()
        driver.find_element_by_id("username").clear()
        driver.find_element_by_id("username").send_keys("student")
        driver.find_element_by_id("password").clear()
        driver.find_element_by_id("password").send_keys("moodle25")
        driver.find_element_by_id("loginbtn").click()
        driver.find_element_by_link_text("My courses").click()
        driver.find_element_by_xpath("//div[@id='course-info-container-39-4']/div/div/a/span[3]/span[2]").click()
        driver.find_element_by_xpath("//a[@onclick='']").click()
        driver.find_element_by_id("single_button69e749d40debc7").click()
        driver.find_element_by_id("q153:1_sub1_answer").click()
        driver.find_element_by_id("q153:1_sub1_answer").clear()
        driver.find_element_by_id("q153:1_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:1_sub2_answer").click()
        driver.find_element_by_id("q153:1_sub2_answer").clear()
        driver.find_element_by_id("q153:1_sub2_answer").send_keys("2")
        driver.find_element_by_id("q153:1_sub3_answer").click()
        driver.find_element_by_id("q153:1_sub3_answer").clear()
        driver.find_element_by_id("q153:1_sub3_answer").send_keys("2")
        driver.find_element_by_id("q153:1_sub4_answer").click()
        driver.find_element_by_id("q153:1_sub4_answer").clear()
        driver.find_element_by_id("q153:1_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:2_sub3_answer").click()
        driver.find_element_by_id("q153:2_sub3_answer").clear()
        driver.find_element_by_id("q153:2_sub3_answer").send_keys("2")
        driver.find_element_by_id("q153:2_sub2_answer").click()
        driver.find_element_by_id("q153:2_sub2_answer").clear()
        driver.find_element_by_id("q153:2_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:2_sub1_answer").click()
        driver.find_element_by_id("q153:2_sub1_answer").clear()
        driver.find_element_by_id("q153:2_sub1_answer").send_keys("4")
        driver.find_element_by_id("q153:3_sub2_answer").click()
        driver.find_element_by_id("q153:3_sub2_answer").clear()
        driver.find_element_by_id("q153:3_sub2_answer").send_keys("2")
        driver.find_element_by_id("q153:3_sub1_answer").click()
        driver.find_element_by_id("q153:3_sub1_answer").clear()
        driver.find_element_by_id("q153:3_sub1_answer").send_keys("2")
        driver.find_element_by_id("q153:3_sub3_answer").click()
        driver.find_element_by_id("q153:3_sub3_answer").clear()
        driver.find_element_by_id("q153:3_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:3_sub4_answer").click()
        driver.find_element_by_id("q153:3_sub4_answer").clear()
        driver.find_element_by_id("q153:3_sub4_answer").send_keys("2")
        driver.find_element_by_id("q153:4_sub2_answer").click()
        driver.find_element_by_id("q153:4_sub2_answer").clear()
        driver.find_element_by_id("q153:4_sub2_answer").send_keys("2")
        driver.find_element_by_id("q153:4_sub3_answer").click()
        driver.find_element_by_id("q153:4_sub3_answer").clear()
        driver.find_element_by_id("q153:4_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:4_sub1_answer").click()
        driver.find_element_by_id("q153:4_sub1_answer").clear()
        driver.find_element_by_id("q153:4_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:4_sub4_answer").click()
        driver.find_element_by_id("q153:4_sub4_answer").clear()
        driver.find_element_by_id("q153:4_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:5_sub1_answer").click()
        driver.find_element_by_id("q153:5_sub1_answer").clear()
        driver.find_element_by_id("q153:5_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:5_sub2_answer").click()
        driver.find_element_by_id("q153:5_sub2_answer").clear()
        driver.find_element_by_id("q153:5_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:5_sub3_answer").click()
        driver.find_element_by_id("q153:5_sub3_answer").clear()
        driver.find_element_by_id("q153:5_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:6_sub1_answer").click()
        driver.find_element_by_id("q153:6_sub1_answer").clear()
        driver.find_element_by_id("q153:6_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:6_sub2_answer").click()
        driver.find_element_by_id("q153:6_sub2_answer").clear()
        driver.find_element_by_id("q153:6_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:6_sub3_answer").click()
        driver.find_element_by_id("q153:6_sub3_answer").clear()
        driver.find_element_by_id("q153:6_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:7_sub1_answer").click()
        driver.find_element_by_id("q153:7_sub1_answer").clear()
        driver.find_element_by_id("q153:7_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:7_sub2_answer").click()
        driver.find_element_by_id("q153:7_sub2_answer").clear()
        driver.find_element_by_id("q153:7_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:7_sub3_answer").click()
        driver.find_element_by_id("q153:7_sub3_answer").clear()
        driver.find_element_by_id("q153:7_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:7_sub4_answer").click()
        driver.find_element_by_id("q153:7_sub4_answer").clear()
        driver.find_element_by_id("q153:7_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:8_sub1_answer").click()
        driver.find_element_by_id("q153:8_sub1_answer").clear()
        driver.find_element_by_id("q153:8_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:8_sub2_answer").click()
        driver.find_element_by_id("q153:8_sub2_answer").clear()
        driver.find_element_by_id("q153:8_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:8_sub3_answer").click()
        driver.find_element_by_id("q153:8_sub3_answer").clear()
        driver.find_element_by_id("q153:8_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:8_sub4_answer").click()
        driver.find_element_by_id("q153:8_sub4_answer").clear()
        driver.find_element_by_id("q153:8_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:9_sub1_answer").click()
        driver.find_element_by_id("q153:9_sub1_answer").clear()
        driver.find_element_by_id("q153:9_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:9_sub2_answer").click()
        driver.find_element_by_id("q153:9_sub2_answer").clear()
        driver.find_element_by_id("q153:9_sub2_answer").send_keys("2")
        driver.find_element_by_id("q153:9_sub3_answer").click()
        driver.find_element_by_id("q153:9_sub3_answer").clear()
        driver.find_element_by_id("q153:9_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:9_sub4_answer").click()
        driver.find_element_by_id("q153:9_sub4_answer").clear()
        driver.find_element_by_id("q153:9_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:10_sub1_answer").click()
        driver.find_element_by_id("q153:10_sub1_answer").clear()
        driver.find_element_by_id("q153:10_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:10_sub2_answer").click()
        driver.find_element_by_id("q153:10_sub2_answer").clear()
        driver.find_element_by_id("q153:10_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:10_sub3_answer").click()
        driver.find_element_by_id("q153:10_sub3_answer").clear()
        driver.find_element_by_id("q153:10_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:10_sub4_answer").click()
        driver.find_element_by_id("q153:10_sub4_answer").clear()
        driver.find_element_by_id("q153:10_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:11_sub1_answer").click()
        driver.find_element_by_id("q153:11_sub1_answer").clear()
        driver.find_element_by_id("q153:11_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:11_sub2_answer").click()
        driver.find_element_by_id("q153:11_sub2_answer").clear()
        driver.find_element_by_id("q153:11_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:11_sub3_answer").click()
        driver.find_element_by_id("q153:11_sub3_answer").clear()
        driver.find_element_by_id("q153:11_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:11_sub4_answer").click()
        driver.find_element_by_id("q153:11_sub4_answer").clear()
        driver.find_element_by_id("q153:11_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:12_sub1_answer").click()
        driver.find_element_by_id("q153:12_sub1_answer").clear()
        driver.find_element_by_id("q153:12_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:12_sub2_answer").click()
        driver.find_element_by_id("q153:12_sub2_answer").clear()
        driver.find_element_by_id("q153:12_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:12_sub3_answer").click()
        driver.find_element_by_id("q153:12_sub3_answer").clear()
        driver.find_element_by_id("q153:12_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:12_sub4_answer").click()
        driver.find_element_by_id("q153:12_sub4_answer").clear()
        driver.find_element_by_id("q153:12_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:13_sub1_answer").click()
        driver.find_element_by_id("q153:13_sub1_answer").clear()
        driver.find_element_by_id("q153:13_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:13_sub2_answer").click()
        driver.find_element_by_id("q153:13_sub2_answer").clear()
        driver.find_element_by_id("q153:13_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:13_sub3_answer").click()
        driver.find_element_by_id("q153:13_sub3_answer").clear()
        driver.find_element_by_id("q153:13_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:14_sub1_answer").click()
        driver.find_element_by_id("q153:14_sub1_answer").clear()
        driver.find_element_by_id("q153:14_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:14_sub2_answer").click()
        driver.find_element_by_id("q153:14_sub2_answer").clear()
        driver.find_element_by_id("q153:14_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:14_sub3_answer").click()
        driver.find_element_by_id("q153:14_sub3_answer").clear()
        driver.find_element_by_id("q153:14_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:15_sub1_answer").click()
        driver.find_element_by_id("q153:15_sub1_answer").clear()
        driver.find_element_by_id("q153:15_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:15_sub2_answer").click()
        driver.find_element_by_id("q153:15_sub2_answer").clear()
        driver.find_element_by_id("q153:15_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:15_sub3_answer").click()
        driver.find_element_by_id("q153:15_sub3_answer").clear()
        driver.find_element_by_id("q153:15_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:15_sub4_answer").click()
        driver.find_element_by_id("q153:15_sub4_answer").clear()
        driver.find_element_by_id("q153:15_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:16_sub1_answer").click()
        driver.find_element_by_id("q153:16_sub1_answer").clear()
        driver.find_element_by_id("q153:16_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:16_sub2_answer").click()
        driver.find_element_by_id("q153:16_sub2_answer").clear()
        driver.find_element_by_id("q153:16_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:16_sub3_answer").click()
        driver.find_element_by_id("q153:16_sub3_answer").clear()
        driver.find_element_by_id("q153:16_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:17_sub1_answer").click()
        driver.find_element_by_id("q153:17_sub1_answer").clear()
        driver.find_element_by_id("q153:17_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:17_sub2_answer").click()
        driver.find_element_by_id("q153:17_sub2_answer").clear()
        driver.find_element_by_id("q153:17_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:17_sub3_answer").click()
        driver.find_element_by_id("q153:17_sub3_answer").clear()
        driver.find_element_by_id("q153:17_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:17_sub4_answer").click()
        driver.find_element_by_id("q153:17_sub4_answer").clear()
        driver.find_element_by_id("q153:17_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:18_sub1_answer").click()
        driver.find_element_by_id("q153:18_sub1_answer").clear()
        driver.find_element_by_id("q153:18_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:18_sub2_answer").click()
        driver.find_element_by_id("q153:18_sub2_answer").clear()
        driver.find_element_by_id("q153:18_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:18_sub3_answer").click()
        driver.find_element_by_id("q153:18_sub3_answer").clear()
        driver.find_element_by_id("q153:18_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:19_sub1_answer").click()
        driver.find_element_by_id("q153:19_sub1_answer").clear()
        driver.find_element_by_id("q153:19_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:19_sub2_answer").click()
        driver.find_element_by_id("q153:19_sub2_answer").clear()
        driver.find_element_by_id("q153:19_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:19_sub3_answer").click()
        driver.find_element_by_id("q153:19_sub3_answer").clear()
        driver.find_element_by_id("q153:19_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:19_sub4_answer").click()
        driver.find_element_by_id("q153:19_sub4_answer").clear()
        driver.find_element_by_id("q153:19_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:20_sub1_answer").click()
        driver.find_element_by_id("q153:20_sub1_answer").clear()
        driver.find_element_by_id("q153:20_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:20_sub5_answer").click()
        driver.find_element_by_id("q153:20_sub5_answer").clear()
        driver.find_element_by_id("q153:20_sub5_answer").send_keys("1")
        driver.find_element_by_id("q153:20_sub2_answer").click()
        driver.find_element_by_id("q153:20_sub2_answer").clear()
        driver.find_element_by_id("q153:20_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:20_sub3_answer").click()
        driver.find_element_by_id("q153:20_sub3_answer").clear()
        driver.find_element_by_id("q153:20_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:20_sub4_answer").click()
        driver.find_element_by_id("q153:20_sub4_answer").clear()
        driver.find_element_by_id("q153:20_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:21_sub1_answer").click()
        driver.find_element_by_id("q153:21_sub1_answer").clear()
        driver.find_element_by_id("q153:21_sub1_answer").send_keys("2")
        driver.find_element_by_id("q153:21_sub2_answer").click()
        driver.find_element_by_id("q153:21_sub2_answer").clear()
        driver.find_element_by_id("q153:21_sub2_answer").send_keys("3")
        driver.find_element_by_id("q153:21_sub3_answer").click()
        driver.find_element_by_id("q153:21_sub3_answer").clear()
        driver.find_element_by_id("q153:21_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:21_sub4_answer").click()
        driver.find_element_by_id("q153:21_sub4_answer").clear()
        driver.find_element_by_id("q153:21_sub4_answer").send_keys("2")
        driver.find_element_by_id("q153:22_sub1_answer").click()
        driver.find_element_by_id("q153:22_sub1_answer").clear()
        driver.find_element_by_id("q153:22_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:22_sub2_answer").click()
        driver.find_element_by_id("q153:22_sub2_answer").clear()
        driver.find_element_by_id("q153:22_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:22_sub3_answer").click()
        driver.find_element_by_id("q153:22_sub3_answer").clear()
        driver.find_element_by_id("q153:22_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:22_sub4_answer").click()
        driver.find_element_by_id("q153:22_sub4_answer").clear()
        driver.find_element_by_id("q153:22_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:23_sub1_answer").click()
        driver.find_element_by_id("q153:23_sub1_answer").clear()
        driver.find_element_by_id("q153:23_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:23_sub2_answer").click()
        driver.find_element_by_id("q153:23_sub2_answer").clear()
        driver.find_element_by_id("q153:23_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:23_sub3_answer").click()
        driver.find_element_by_id("q153:23_sub3_answer").clear()
        driver.find_element_by_id("q153:23_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:23_sub4_answer").click()
        driver.find_element_by_id("q153:23_sub4_answer").clear()
        driver.find_element_by_id("q153:23_sub4_answer").send_keys("1")
        driver.find_element_by_id("q153:24_sub1_answer").click()
        driver.find_element_by_id("q153:24_sub1_answer").clear()
        driver.find_element_by_id("q153:24_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:24_sub2_answer").click()
        driver.find_element_by_id("q153:24_sub2_answer").clear()
        driver.find_element_by_id("q153:24_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:24_sub3_answer").click()
        driver.find_element_by_id("q153:24_sub3_answer").clear()
        driver.find_element_by_id("q153:24_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:25_sub1_answer").click()
        driver.find_element_by_id("q153:25_sub1_answer").clear()
        driver.find_element_by_id("q153:25_sub1_answer").send_keys("1")
        driver.find_element_by_id("q153:25_sub2_answer").click()
        driver.find_element_by_id("q153:25_sub2_answer").clear()
        driver.find_element_by_id("q153:25_sub2_answer").send_keys("1")
        driver.find_element_by_id("q153:25_sub3_answer").click()
        driver.find_element_by_id("q153:25_sub3_answer").clear()
        driver.find_element_by_id("q153:25_sub3_answer").send_keys("1")
        driver.find_element_by_id("q153:25_sub4_answer").click()
        driver.find_element_by_id("q153:25_sub4_answer").clear()
        driver.find_element_by_id("q153:25_sub4_answer").send_keys("1")
        driver.find_element_by_id("mod_quiz-next-nav").click()
        driver.find_element_by_xpath("//div[@id='region-main']/div[2]/div[2]/table/tbody").click()
        try: self.assertEqual("Answer saved", driver.find_element_by_xpath("//tbody[@id='yui_3_18_1_1_1776765578748_50']/tr[23]/td[2]").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_id("single_button69e74a8de01189").click()
        driver.find_element_by_xpath("//body[@id='page-mod-quiz-summary']/div[6]/div[2]/div/div/div").click()
        try: self.assertRegexpMatches(driver.find_element_by_id("11-modal-title").text, r"^Submit all your answers and finish[\s\S]$")
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_xpath("//div[@id='yui_3_18_1_1_1776765578748_58']/div[2]").click()
        try: self.assertEqual(u"Once you submit your answers, you won’t be able to change them.", driver.find_element_by_xpath("//div[@id='yui_3_18_1_1_1776765578748_62']/div/div").text)
        except AssertionError as e: self.verificationErrors.append(str(e))
        driver.find_element_by_xpath("//div[@id='yui_3_18_1_1_1776765578748_58']/div[3]/button[2]").click()
        driver.find_element_by_xpath("//body[@id='page-mod-quiz-summary']/div[5]/div[2]/div/div/div[3]/button[2]").click()
        driver.find_element_by_xpath("//div[@id='region-main']/div[2]/div[2]/a").click()
        driver.find_element_by_id("user-menu-toggle").click()
        driver.find_element_by_link_text("Log out").click()
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException as e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
